AWSTemplateFormatVersion: "2010-09-09"
Description: Main template with three nested stacks

Parameters:
  BucketNamePrefix:
    Type: String
    Default: cfn-automation-poc-staging

Resources:
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    Properties:
      TemplateURL: compute/compute.yaml
      Parameters:
        BucketName: !Sub "${BucketNamePrefix}-nested-one-staging"

  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    Properties:
      TemplateURL: monitoring/monitoring.yaml
      Parameters:
        BucketName: !Sub "${BucketNamePrefix}-nested-two-staging"

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    Properties:
      TemplateURL: network/network.yaml
      Parameters:
        BucketName: !Sub "${BucketNamePrefix}-nested-three-staging"

  ParentS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-nested-three-staging-parent-bucket"
      Tags:
        - Key: Template
          Value: Parent
        - Key: Environment
          Value: Automation-PoC-Staging
