AWSTemplateFormatVersion: "2010-09-09"
Description: Main template with three nested stacks

Parameters:
  BucketNamePrefix:
    Type: String
    Default: cfn-automation-poc

Resources:
  ComputeStack:
    Type: AWS::CloudFormation::Stac
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-automation-github-actions-poc/compute-stack/child-1.yaml
      Parameters:
        BucketName: !Sub "${BucketNamePrefix}-nested-one"

  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-automation-github-actions-poc/monitoring-stack/child-2.yaml
      Parameters:
        BucketName: !Sub "${BucketNamePrefix}-nested-two"

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-automation-github-actions-poc/network-stack/child-3.yaml
      Parameters:
        BucketName: !Sub "${BucketNamePrefix}-nested-three"
