AWSTemplateFormatVersion: "2010-09-09"
Description: First nested template

Parameters:
  BucketName:
    Type: String

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: Template
          Value: Child-1
