name: check for cloudformation lint errors before deploy

on:
  pull_request:
    paths:
      - "**.yaml"
      - "**.yml"

jobs:
  cfn-lint:
    runs-on: [self-hosted, linux, ARM64, cfn-poc]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run cfn-lint
        run: |
          pwd
          ls -al
          # find all yaml files (*.yaml and *.yml) in the repository and run cfn-lint on them except for the ones in the .github directory
          find . -path "./.github" -prune -o -type f \( -name '*.yaml' -o -name '*.yml' \) -exec cfn-lint -t {} +
