name: Deploy CloudFormation templates

on:
  pull_request:
    types:
      - closed
    branches:
      - "iac-release/customer/dev"
    paths:
      - "dev/**.yaml"
      - "dev/**.yml"
      - ".github/workflows/deploy-dev.yaml"
      - ".github/workflows/cfn-lint.yaml"

jobs:
  package-and-deploy-dev:
    if: github.event.pull_request.merged == true
    name: Package CloudFormation templates to S3
    environment: Dev
    runs-on: [self-hosted, linux, ARM64, cfn-poc]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package CloudFormation templates to S3
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          echo "Packaging CloudFormation templates to S3"
          aws cloudformation package \
            --template-file dev/parent.yaml \
            --s3-bucket ${{ secrets.S3_BUCKET }} \
            --s3-prefix ${{ secrets.S3_PREFIX }} \
            --output-template-file customer-cfn-stack-tpl-${{ secrets.S3_PREFIX }}-$TIMESTAMP.yaml

      - name: Deploy ${{ matrix.environment }} stack
        run: |
          aws cloudformation deploy \
            --template-file customer-cfn-stack-tpl-${{ secrets.S3_PREFIX }}-$TIMESTAMP.yaml \
            --stack-name "iac-customer-${{ secrets.S3_PREFIX }}" \
            --capabilities CAPABILITY_NAMED_IAM
          rm -rf customer-cfn-stack-tpl-${{ secrets.S3_PREFIX }}-$TIMESTAMP.yaml
