name: Deploy CloudFormation templates

on:
  pull_request:
    types:
      - closed
    branches:
      - "iac-release/customer/dev"
    paths:
      - "dev/**.yaml"
      - "dev/**.yml"

jobs:
  package-to-s3:
    if: github.event.pull_request.merged == true
    name: Package CloudFormation templates to S3
    environment: Stage
    runs-on: [self-hosted, linux, ARM64, cfn-poc]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package CloudFormation templates to S3
        run: |
          echo "Packaging CloudFormation templates to S3 dev"
          echo ${{ matrix.environment }}
          aws cloudformation package \
            --template-file dev/parent.yaml \
            --s3-bucket cfn-automation-github-actions-poc/dev \
            --s3-prefix "${{ matrix.environment }}/" \
            --output-template-file packaged-parent.yaml
